name: Auto Author Assign

on:
  pull_request:
    branches: [develop]
    types: [opened, reopened]

jobs:
  assign-author:
    runs-on: saritasa-rocks-eks

    steps:
      - uses: toshimaru/auto-author-assign@v1.6.2
