name: Run build

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: saritasa-rocks-eks

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build:dev
